#pragma once

#define WINDOW_CLASS_NAME L"Blaster Master"
#define MAIN_WINDOW_TITLE L"Blaster Master"

#define BACKGROUND_COLOR D3DCOLOR_XRGB(255, 255, 225)
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define MAX_FRAME_RATE 60

#define ID_TEXTURES_PLAYER 0
#define ID_TEXTURES_ENEMIES 1

#define ID_TEX_BBOX -100